### ISSUE TITLE
Not `factory_bot_instruments` in RubyGems

### ISSUE THREAD

**Issue by cheerfulstoic** [shiroyasha/factory_girl_instruments#3]
I can see `factory_girl_instruments` in RubyGems, but not `factory_bot_instruments`:

https://rubygems.org/gems/factory_bot_instruments

In order to make the gem work I need to `gem 'factory_bot_instruments', github: 'shiroyasha/factory_bot_instruments'`.  Could the `factory_bot_instruments` gem be published?

**Comment by shiroyasha** [comment]
Thanks for opening the issue @cheerfulstoic, it seems it slipped out of my schedule to publish it.

I can probably achieve it during this week.

**Comment by cheerfulstoic** [comment]
:+1: Cheers

**Comment by cheerfulstoic** [comment]
(and thanks for this gem, by the way.  It can definitely be tricky to debug `factory_bot` sometimes without it)

**Comment by cabello** [comment]
This gem is great, it helped me debug some callback/association hell we had created for ourselves.

**Comment by schmijos** [comment]
Well… I just did it (before someone else does) and added you (igisar@gmail.com) as an owner. Please remove me and my company from the owner list as soon as you take over.

**Comment by strika** [comment]
This issue can be closed.

**Comment by schmijos** [comment]
Ah, that's why.
